### ISSUE TITLE
Adicionar imagem de Genero .none 

### ISSUE THREAD

**Issue by gusholz** [Apple-Developer-Residency-IFCE/LoveMyCapibara#15]
Já foi requisitado aos designers criar uma nova imagem para o caso do gênero nenhum. Atualmente, essa imagem ainda não existe e nesse caso ocorre uma quebra do layout.

**Comment by Jwinny** [comment]
Uma sugestão seria quando for .none colocar um `Spacer(minLength: tamanhoDoIcone)` para o design persistir.
